const productsData = {
  bestSellers: [],
  recommended: [
    { id: 1, name: "Product 1", price: "$10", image: "path/to/image1.jpg" },  
    { id: 2, name: "Product 2", price: "$20", image: "path/to/image2.jpg" },
    { id: 3, name: "Product 3", price: "$30", image: "path/to/image3.jpg" },
    { id: 4, name: "Product 4", price: "$40", image: "path/to/image4.jpg" },
    // { id: 5, name: "Product 5", price: "$50", image: "path/to/image5.jpg" },
    // Add more products as needed
  ],
  categories: [
    {
      id: 1,
      name: "Makanan Kering",
      products: [
        {
          id: 1,
          name: "Rebo kuaci",
          description: "ini adalah Rebo kuaci",
          price: "14875",
          image: "images/rebo-kuaci.png",
          sold: 0,
        },
        {
          id: 2,
          name: "Kusuka keripik emping",
          description: "ini adalah Kusuka keripik emping",
          price: "8544",
          image: "images/kusuka-keripik-emping.png",
          sold: 0,
        },
        {
          id: 3,
          name: "Qtela",
          description: "ini adalah Qtela",
          price: "9200",
          image: "images/qtela.png",
          sold: 0,
        },
      ],
    },
    {
      id: 2,
      name: "Minuman",
      products: [
        {
          id: 4,
          name: "Teh kotak",
          description: "ini adalah Teh kotak",
          price: "3500",
          image: "images/teh-kotak.png",
          sold: 0,
        },
        {
          id: 5,
          name: "Pocari sweat",
          description: "ini adalah Pocari sweat",
          price: "23900",
          image: "images/pocari-sweat.png",
          sold: 0,
        },
        {
          id: 6,
          name: "Buahvita jambu",
          description: "ini adalah Buahvita jambu",
          price: "25415",
          image: "images/buavita-jambu.png",
          sold: 0,
        },
      ],
    },
    {
      id: 3,
      name: "Produk Kesehatan dan Kecantikan",
      products: [
        {
          id: 7,
          name: "Nivea deodorant",
          description: "ini adalah Nivea deodorant",
          price: "12480",
          image: "images/nivea-deodorant.png",
          sold: 0,
        },
        {
          id: 8,
          name: "Vaseline body lotion",
          description: "ini adalah Vaseline body lotion",
          price: "55900",
          image: "images/vaseline-body-lotion.png",
          sold: 0,
        },
        {
          id: 9,
          name: "Shinzui sakura body lotion",
          description: "ini adalah Shinzui sakura body lotion",
          price: "22300",
          image: "images/shinzui-sakura-body-lotion.png",
          sold: 0,
        },
      ],
    },
    {
      id: 4,
      name: "Produk Rumah Tangga",
      products: [
        {
          id: 10,
          name: "ABC Alkaline AAA baterai",
          description: "ini adalah ABC alkaline AAA baterai",
          price: "19800",
          image: "images/abc-alkaline-aaa-baterai.png",
          sold: 0,
        },
        {
          id: 11,
          name: "Joyko cutter",
          description: "ini adalah Joyko cutter",
          price: "17000",
          image: "images/joyko-cutter.png",
          sold: 0,
        },
        {
          id: 12,
          name: "Uhu lem tube",
          description: "ini adalah Uhu lem tube",
          price: "19500",
          image: "images/uhu-lem-tube.png",
          sold: 0,
        },
      ],
    },
    {
      id: 5,
      name: "Produk Pembersih",
      products: [
        {
          id: 13,
          name: "Bayclin pemutih pakaian",
          description: "ini adalah Bayclin pemutih pakaian",
          price: "23900",
          image: "images/bayclin-pemutih-pakaian.png",
          sold: 0,
        },
        {
          id: 14,
          name: "Mama lemon jeruk nipis",
          description: "ini adalah Mama lemon jeruk nipis",
          price: "14800",
          image: "images/mama-lemon-jeruk-nipis.png",
          sold: 0,
        },
        {
          id: 15,
          name: "Mr muscle pembersih serba guna",
          description: "ini adalah Mr muscle pembersih serba guna",
          price: "8500",
          image: "images/mr-muscle-pembersih-serba-guna.png",
          sold: 0,
        },
      ],
    },
    {
      id: 6,
      name: "Produk Rokok",
      products: [
        {
          id: 16,
          name: "Rokok 169 kretek",
          description: "ini adalah Rokok 169 kretek",
          price: "76650",
          image: "images/rokok-169-kretek.png",
          sold: 0,
        },
        {
          id: 17,
          name: "Rokok sampoerna mild",
          description: "ini adalah Rokok sampoerna mild",
          price: "300500",
          image: "images/rokok-sampoerna-mild.png",
          sold: 0,
        },
        {
          id: 18,
          name: "Rokok sampoerna splash",
          description: "ini adalah Rokok sampoerna splash",
          price: "218000",
          image: "images/rokok-sampoerna-splash.png",
          sold: 0,
        },
      ],
    },
    {
      id: 7,
      name: "Bahan Pokok",
      products: [
        {
          id: 19,
          name: "Sunco minyak goreng",
          description: "ini adalah Sunco minyak goreng",
          price: "35900",
          image: "images/sunco-minyak-goreng.png",
          sold: 0,
        },
        {
          id: 20,
          name: "Gulaku premium gula pasir",
          description: "ini adalah Gulaku premium gula pasir",
          price: "18900",
          image: "images/gulaku-premium-gula-pasir.png",
          sold: 0,
        },
        {
          id: 21,
          name: "Rose brand tepung tapioka",
          description: "ini adalah Rose brand tepung tapioka",
          price: "10800",
          image: "images/rose-brand-tepung-tapioka.png",
          sold: 0,
        },
      ],
    },
    {
      id: 8,
      name: "Barang Kemasan dan Plastik",
      products: [
        {
          id: 22,
          name: "Bagus zipper bag plastik",
          description: "ini adalah Bagus zipper bag plastik",
          price: "50400",
          image: "images/bagus-zipper-bag-plastik.png",
          sold: 0,
        },
      ],
    },
    {
      id: 9,
      name: "Produk Kebersihan Tubuh",
      products: [
        {
          id: 23,
          name: "Formula sikat gigi",
          description: "ini adalah Formula sikat gigi",
          price: "9900",
          image: "images/formula-sikat-gigi.png",
          sold: 0,
        },
        {
          id: 24,
          name: "Nuvo sabun cuci tangan",
          description: "ini adalah Nuvo sabun cuci tangan",
          price: "11900",
          image: "images/nuvo-sabun-cuci-tangan.png",
          sold: 0,
        },
        {
          id: 25,
          name: "Tresemme shampoo keratin",
          description: "ini adalah Tresemme shampoo keratin",
          price: "37700",
          image: "images/tresemme-shampoo-keratin.png",
          sold: 0,
        },
      ],
    },
    {
      id: 10,
      name: "Produk P3K (Pertolongan Pertama Pada Kecelakaan)",
      products: [
        {
          id: 26,
          name: "Handsaplast transparan",
          description: "ini adalah handsaplast transparan",
          price: "8836",
          image: "images/handsaplast-transparan.png",
          sold: 0,
        },
      ],
    },
    {
      id: 11,
      name: "Gadget dan Elektronik",
      products: [
        {
          id: 27,
          name: "Myvo classic 9W",
          description: "ini adalah Myvo classic 9w",
          price: "17300",
          image: "images/myvo-classic-9w.png",
          sold: 0,
        },
      ],
    },
  ],
};

export default productsData;
